# Generated by Django 4.1 on 2022-09-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='question',
        ),
        migrations.AddField(
            model_name='school',
            name='question_num',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
