# Generated by Django 4.1 on 2022-09-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='display_name',
        ),
    ]
