# Generated by Django 4.1.1 on 2022-10-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='school',
            name='ch_levelup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
