# Generated by Django 4.1 on 2022-09-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypt_hunt', '0001_initial'),
        ('accounts', '0002_rename_name_school_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='ch_level',
        ),
        migrations.AddField(
            model_name='school',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crypt_hunt.question'),
        ),
    ]
