# Generated by Django 4.1 on 2022-09-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_school_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='account',
        ),
    ]
