# Generated by Django 4.1.1 on 2022-10-05 07:14

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_num', models.SmallIntegerField()),
                ('question', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('answer', models.CharField(max_length=100)),
                ('image_paths_list', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField(default=0)),
                ('contents', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('ODT', 'Outdated'), ('COR', 'Correct'), ('INC', 'Incorrect')], default='INC', max_length=3)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('school', models.CharField(max_length=100)),
                ('user_id', models.CharField(default=None, max_length=100, null=True)),
                ('ip_address', models.CharField(max_length=100)),
            ],
        ),
    ]
