# Generated by Django 4.1 on 2022-09-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypt_hunt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='serial_number',
            new_name='serial_num',
        ),
    ]
