# Generated by Django 4.1.1 on 2022-10-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt_hunt', '0003_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='time_submitted',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='for_question',
        ),
        migrations.AddField(
            model_name='submission',
            name='question_num',
            field=models.IntegerField(default=0),
        ),
    ]
