# Generated by Django 4.1.1 on 2022-10-03 15:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt_hunt', '0005_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_paths',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
