# Generated by Django 4.1.1 on 2022-10-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypt_hunt', '0006_question_image_paths_alter_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image_paths',
            new_name='image_paths_list',
        ),
    ]
