# Generated by Django 4.1.1 on 2022-10-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt_hunt', '0007_rename_image_paths_question_image_paths_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_paths_list',
            field=models.TextField(default=None, null=True),
        ),
    ]
