# Generated by Django 4.1.1 on 2022-10-03 15:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt_hunt', '0008_alter_question_image_paths_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
    ]
