# Generated by Django 4.1.1 on 2022-10-03 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crypt_hunt', '0010_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
