# Generated by Django 4.1.1 on 2022-10-03 15:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypt_hunt', '0012_remove_question_question_uuid_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
