# Generated by Django 4.1.1 on 2022-10-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt_hunt', '0013_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_paths_list',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
