# Generated by Django 4.1.1 on 2022-10-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac_man', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacmanplayer',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
