# Generated by Django 4.1 on 2022-09-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac_man', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacmanplayer',
            name='num_attempts',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
