EVENT_SLUGS = [
    'hackathon',
    'bot-trading',
    'senior-quiz',
    'middle-quiz',
    'junior-quiz',
    'crypt-hunt',
    'competitive-gaming',
    'photoshop-battles',
    'ad-making',
    'programming',
    'drone-racing',
    'web-design',
    'pac-man',
]